apiVersion: v1
kind: Service
metadata:
  name: map
  namespace: gameon-system
  labels:
    app: gameon-map
spec:
  type: ClusterIP
  ports:
  - port: 9080
    name: http
  selector:
    app: gameon-map
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-deploy
  namespace: gameon-system
  labels:
    app: gameon-map
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gameon-map
  template:
    metadata:
      labels:
        app: gameon-map
    spec:
      volumes:
      - name: certificate
        secret:
          secretName: global-cert
      containers:
      - name: map
        image: gameontext/gameon-map:lastgood
        imagePullPolicy: IfNotPresent
        ports:
        - name: map
          containerPort: 9080
        readinessProbe:
          httpGet:
            path: /map/v1/health
            port: 9080
          initialDelaySeconds: 40
        volumeMounts:
        - name: certificate
          mountPath: /etc/cert
        envFrom:
        - configMapRef:
            name: global-config
