apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: gameon-system
  labels:
    app: gameon-webapp
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: http
  selector:
    app: gameon-webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
  namespace: gameon-system
  labels:
    app: gameon-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gameon-webapp
  template:
    metadata:
      labels:
        app: gameon-webapp
    spec:
      containers:
      - image: gameontext/gameon-webapp:lastgood
        imagePullPolicy: IfNotPresent
        name: webapp
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 40
